eval:
  - draft_k:
      - 12
      - 0
    tokens:
      - 512
    draft:
      - amd/PARD-Llama-3.2-1B
    target:
      - meta-llama/Llama-3.1-8B-Instruct
    benchmark:
      - humaneval
      - gsm8k
    para:
      - true
    nc:
      - false
    maxtune:
      - true
